FROM python:3.6


RUN     apt-get update && \
        apt-get upgrade -y && \
        apt-get install -y --no-install-recommends build-essential cmake git pkg-config

COPY . /app
WORKDIR /app

RUN	pip3 install -r requirements_temp.txt

#ENTRYPOINT ["python3.6"]
#CMD ["app.py"]

