#--------------------
# For resin RaspberryPi3
#FROM resin/raspberrypi3-python:3.6
FROM demosense/raspberrypi3-opencv
#--------------------


# generate /root/work directory
WORKDIR /root/work

# copy .bashrc from host to target /root directory
ADD .bashrc /root

# setup environment variables?
#ENV DISPLAY :0


#--------------------
# For OpenCV

RUN     apt-get update && \
        apt-get upgrade -y && \

	pip install --upgrade pip && \
        pip3 install dlib && \
        pip3 install numpy scipy matplotlib scikit-learn && \
	pip3 install Pillow tensorflow vlc pymongo pprint && \
	pip3 install google-cloud-speech==0.35.0 && \
	pip3 install requests Flask pic ffpyplayer

        #pip3 install dlib numpy scipy matplotlib sckikit-image scikit-learn && \
	#pip3 install google-cloud-vision==0.30.1 && \
#tensorflow-1.11.0-cp35-none-linux_armv7l.whl

CMD /bin/bash

#RUN cd /root; git clone https://github.com/opencv/opencv; cd /root/opencv; mkdir build; cd build; cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..; make; make install
#-----------------

